version: "3.9"

services:
  decoilbase:
    build:
      context: .
      dockerfile: Dockerfile_decoil_base_r411
      args:
       VERSION_BASE: ${VERSION_BASE}
    platform: linux/amd64
    image: decoil-base:${VERSION_BASE}
